version: 1.0-{build}
os: Visual Studio 2015
environment:
  matrix:
    - nodejs_version: 10.15
      platform: x64
      npm_version: 6.4.1
      nan_version: 2.13.2
      pre_gyp_version: 0.12.0
    - nodejs_version: 8.6
      platform: x64
      npm_version: 6.4.1
      nan_version: 2.13.2    
      pre_gyp_version: 0.12.0      
    - nodejs_version: 6.11
      platform: x64
      npm_version: 6.4.1
      nan_version: 2.13.2
      pre_gyp_version: 0.12.0      
    - nodejs_version: 4.8
      platform: x64
      npm_version: 5.5.1
      nan_version: 2.7.0
      pre_gyp_version: 0.6.39      

cache:
  - '%APPDATA%\npm-cache'
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm@%npm_version%
  - set PATH=%APPDATA%\npm;%PATH%
  - npm i nan@%nan_version%
  - npm install -g node-pre-gyp@%pre_gyp_version%
  - npm install -g node-pre-gyp-github

build_script:
  - node-pre-gyp configure
  - node-pre-gyp build
  - node-pre-gyp package
test: off
artifacts:
  - path: .\build\stage
for:
  -
    branches:
      only:
        - master
    on_success:
      - ps: |
            if ($env:NODE_PRE_GYP_GITHUB_TOKEN)
            {
                git config --global credential.helper store
                Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:NODE_PRE_GYP_GITHUB_TOKEN):x-oauth-basic@github.com`n"
                git config --global user.email "matthias.dieudonne@gmail.com"
                git config --global user.name "MatthD"
                node-pre-gyp-github publish --release
            }
